# Generated by Django 3.2.13 on 2022-08-07 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20220605_1447'), ('blog', '0003_delete_contact'), ('blog', '0004_alter_post_options'), ('blog', '0005_full_post'), ('blog', '0006_delete_full_post'), ('blog', '0007_post_author'), ('blog', '0008_post_image'), ('blog', '0009_alter_post_image'), ('blog', '0010_alter_post_image'), ('blog', '0011_alter_post_image'), ('blog', '0012_remove_post_image'), ('blog', '0013_post_image'), ('blog', '0014_auto_20220630_2232'), ('blog', '0015_alter_category_options'), ('blog', '0016_auto_20220725_1337'), ('blog', '0017_comment_post'), ('blog', '0018_alter_comment_options'), ('blog', '0019_post_login_required'), ('blog', '0020_rename_login_required_post_login_require')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('counted_views', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='blog/default.jpg', upload_to='blog/')),
                ('category', models.ManyToManyField(to='blog.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('login_require', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('massage', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('approach', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
