# Generated by Django 3.2.13 on 2022-06-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_full_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='full_post',
        ),
    ]
