# Generated by Django 3.2.13 on 2022-07-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
    ]
