# Generated by Django 3.2.13 on 2022-08-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_login_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='login_required',
            new_name='login_require',
        ),
    ]
